/* ====================================================================
 * Copyright (c) 2016 The GmSSL Project.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgment:
 *    "This product includes software developed by the GmSSL Project.
 *    (http://gmssl.org/)"
 *
 * 4. The name "GmSSL Project" must not be used to endorse or promote
 *    products derived from this software without prior written
 *    permission. For written permission, please contact
 *    guanzhi1980@gmail.com.
 *
 * 5. Products derived from this software may not be called "GmSSL"
 *    nor may "GmSSL" appear in their names without prior written
 *    permission of the GmSSL Project.
 *
 * 6. Redistributions of any form whatsoever must retain the following
 *    acknowledgment:
 *    "This product includes software developed by the GmSSL Project
 *    (http://gmssl.org/)"
 *
 * THIS SOFTWARE IS PROVIDED BY THE GmSSL PROJECT ``AS IS'' AND ANY
 * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE GmSSL PROJECT OR
 * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 * ====================================================================
 */

#ifndef HEADER_GMSDF_H
#define HEADER_GMSDF_H

#include <stdio.h>
#include <openssl/sgd.h>
#include <openssl/sdf.h>

#ifdef __cplusplus
extern "C" {
#endif

int SDF_PrintDeviceInfo(FILE *fp, DEVICEINFO *devInfo);
int SDF_PrintRSAPublicKey(FILE *fp, RSArefPublicKey *pk);
int SDF_PrintRSAPrivateKey(FILE *fp, RSArefPrivateKey *pk);
int SDF_PrintECCPublicKey(FILE *fp, ECCrefPublicKey *pk);
int SDF_PrintECCPrivateKey(FILE *fp, ECCrefPrivateKey *pk);
int SDF_PrintECCCipher(FILE *fp, ECCCipher *cipher);
int SDF_PrintECCSignature(FILE *fp, ECCSignature *sig);
char *SDF_GetErrorString(int errno);

/* BEGIN ERROR CODES */
/*
 * The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */

int ERR_load_SDF_strings(void);

/* Error codes for the SDF functions. */

/* Function codes. */
# define SDF_F_SDF_CALCULATEMAC                           100
# define SDF_F_SDF_DECODE_EC_SIGNATURE                    101
# define SDF_F_SDF_DECRYPT                                102
# define SDF_F_SDF_ENCODE_EC_SIGNATURE                    103
# define SDF_F_SDF_ENCRYPT                                104
# define SDF_F_SDF_EXPORTENCPUBLICKEY_ECC                 105
# define SDF_F_SDF_EXPORTENCPUBLICKEY_RSA                 106
# define SDF_F_SDF_EXPORTSIGNPUBLICKEY_ECC                107
# define SDF_F_SDF_EXPORTSIGNPUBLICKEY_RSA                108
# define SDF_F_SDF_EXTERNALDECRYPT_ECC                    109
# define SDF_F_SDF_EXTERNALENCRYPT_ECC                    110
# define SDF_F_SDF_EXTERNALPRIVATEKEYOPERATION_RSA        111
# define SDF_F_SDF_EXTERNALPUBLICKEYOPERATION_RSA         112
# define SDF_F_SDF_EXTERNALSIGN_ECC                       113
# define SDF_F_SDF_EXTERNALVERIFY_ECC                     114
# define SDF_F_SDF_GENERATEKEYPAIR_ECC                    115
# define SDF_F_SDF_GENERATEKEYPAIR_RSA                    116
# define SDF_F_SDF_GENERATEKEYWITHEPK_ECC                 117
# define SDF_F_SDF_GENERATEKEYWITHEPK_RSA                 118
# define SDF_F_SDF_GENERATEKEYWITHIPK_ECC                 119
# define SDF_F_SDF_GENERATEKEYWITHIPK_RSA                 120
# define SDF_F_SDF_GENERATERANDOM                         121
# define SDF_F_SDF_GETDEVICEINFO                          122
# define SDF_F_SDF_GETPRIVATEKEYACCESSRIGHT               142
# define SDF_F_SDF_GET_CIPHER                             123
# define SDF_F_SDF_GET_DIGEST                             124
# define SDF_F_SDF_HASHFINAL                              125
# define SDF_F_SDF_HASHINIT                               126
# define SDF_F_SDF_HASHUPDATE                             127
# define SDF_F_SDF_IMPORTKEY                              128
# define SDF_F_SDF_IMPORTKEYWITHISK_ECC                   129
# define SDF_F_SDF_IMPORTKEYWITHISK_RSA                   130
# define SDF_F_SDF_INTERNALDECRYPT_ECC                    131
# define SDF_F_SDF_INTERNALENCRYPT_ECC                    132
# define SDF_F_SDF_INTERNALPRIVATEKEYOPERATION_RSA        133
# define SDF_F_SDF_INTERNALPUBLICKEYOPERATION_RSA         134
# define SDF_F_SDF_INTERNALSIGN_ECC                       135
# define SDF_F_SDF_INTERNALVERIFY_ECC                     136
# define SDF_F_SDF_LOAD_EC_PRIVATE_KEY                    137
# define SDF_F_SDF_LOAD_EC_PUBLIC_KEY                     138
# define SDF_F_SDF_LOAD_RSA_PRIVATE_KEY                   139
# define SDF_F_SDF_LOAD_RSA_PUBLIC_KEY                    140
# define SDF_F_SDF_OPENDEVICE                             141

/* Reason codes. */
# define SDF_R_BUFFER_TOO_SMALL                           100
# define SDF_R_BUUTER_TOO_SMALL                           101
# define SDF_R_CBCMAC_FAILURE                             102
# define SDF_R_ENGINE_LOAD_KEY_FAILURE                    103
# define SDF_R_GET_PRIVATE_KEY_FAILED                     104
# define SDF_R_GET_PUBLIC_KEY_FAILED                      105
# define SDF_R_INVALID_ALGOR                              106
# define SDF_R_INVALID_EC_CIPHERTEXT                      107
# define SDF_R_INVALID_EC_PRIVATE_KEY                     108
# define SDF_R_INVALID_EC_PUBLIC_KEY                      109
# define SDF_R_INVALID_INPUT_LENGTH                       110
# define SDF_R_INVALID_KEY_HANDLE                         111
# define SDF_R_INVALID_KEY_LENGTH                         112
# define SDF_R_INVALID_KEY_USAGE                          113
# define SDF_R_INVALID_LENGTH                             118
# define SDF_R_INVALID_OPERATION_STATE                    114
# define SDF_R_KEY_TYPE_NOT_MATCH                         115
# define SDF_R_RANDOM_FAILURE                             116
# define SDF_R_SDF_SESSION_NO_ENGINE                      117

# ifdef  __cplusplus
}
# endif
#endif
